### ISSUE TITLE
Question about assets

### ISSUE THREAD

**Issue by Tunnelvisie** [jabuwu/bevy_spine_demos#1]
Hi!

I'm pretty new to Rust and Bevy, but I came across your `bevy_spine` crate and this related repo.

In Blender I have a very simple 3D model of a human with an skeleton/armature rigged to it and some basic textures.

I want to load SkeletonData similar to how you do it in your examples:

```
let skeleton = SkeletonData::new_from_json(
        asset_server.load("owl/export/owl-pro.json"),
        asset_server.load("owl/export/owl.atlas"),
    );
    let skeleton_handle = skeletons.add(skeleton);
```

However, I don't understand how I create these `.json` and `.atlas` files. Could you point me in the right direction on how I can export a my model to obtain this SkeletonData in json and atlas files? 

Thanks

**Comment by jabuwu** [comment]
I'm not sure exactly what you're asking, the problem of loading Blender models is going to be very different from loading Spine rigs. I recommend looking into Bevy's `gltf` support as it may already be what you want.

I'll try to give an overview of how importing assets works in `bevy_spine`.

All assets in Bevy are loaded asynchronously, so you always have to check if these assets have been loaded before they can be used. In the case that there's two files needed for one asset, like in this case, you need either a component or another asset type to track them. I chose to use an asset, instead of a component, because `SkeletonData` can be reused by multiple components, so they shouldn't all need to track loading separately.

When a `SpineBundle` is instantiated, a `SpineLoader` component is attached, along with the `SkeletonData` asset, and a system checks if the `SkeletonData` and its dependent assets have loaded. When everything is loaded, it attaches the `Spine` component. This is really convenient because all systems can assume that if a `Spine` component exists on an entity, then its assets have already loaded, and it's safe to use.

The system that handles all this is `spine_load`
https://github.com/jabuwu/bevy_spine/blob/802be15c37d21a3daccaa2d17ff04c865d5b0214/src/lib.rs#L211

And loading the new assets is in `assets.rs`:
https://github.com/jabuwu/bevy_spine/blob/802be15c37d21a3daccaa2d17ff04c865d5b0214/src/assets.rs

A couple notes on this implementation though:
- Textures are not tracked, and a Spine rig could load and start rendering before textures are loaded
- This process might be greatly simplified in the future [when Bevy introduces asset preprocessing](https://bevyengine.org/news/bevy-0-9/#what-s-next)
- Spawning a Spine rig will always have a frame delay as each `SpineLoader` must do these checks even if the assets are loaded

**Comment by Tunnelvisie** [comment]
Thank you for the thorough response! 

I'll explain a little bit better what I'm trying to do, and then perhaps it makes a bit more sense. I'm going to preface this by saying that I'm new to game development and new to Rust. I normally work mainly in Python/Data Science. Being new to this I'm also still learning about file types, and terminology on both the Rust and Game Dev side. Currently, I have loaded static models/assets into Bevy that I have converted to `.glb` (I think that's basically the same as `.gltf`) using Blender. 

So, some of my question might be easier to solve than I think (maybe not) but I've been searching for a couple of days now and it's difficult to find something I need when I'm not sure about some of the terminology, or if it even exists, or how it works, haha.

What I want to do is the following. I have a dataset with body pose estimation data consisting of coordinates of human joints (hips, knees, ankles, elbows etc). and other points of reference (ears, nose etc.).

Using this information I want to update and animate a character in real time by updating the coordinates of a human figure to which I added an armature with the same bone structure as the body pose data.

To this end I have been able to add an armature to a human figure in Blender, but my first problem is is that there are hardly any examples (none, that I could find) that deal with this type of data in Bevy. And your example with the owl and coin seemed the closest things to even simply loading a rigged model. So, I was simply wondering how you went about exporting that `.json` and `.atlas` file you use in your example.

From reading your response (and since you mentioned gltf) I'm assuming that I'm looking in the wrong place, but since your nice owl example loaded something that looked rigged and subsequently animated on the fly (given mouse gestures), I figured it could be similar. 

If you could give me any points that would be greatly appreciated, but I understand that I'm probably in the wrong place, haha.

Thanks!

**Comment by Tunnelvisie** [comment]
I was able to resolve my issue after a lot of trial and error. 

My final answer was posted here: https://github.com/bevyengine/bevy/discussions/7058
